# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gelambin <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/07 09:46:47 by gelambin          #+#    #+#              #
#    Updated: 2017/11/07 19:10:41 by gelambin         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

all: $(NAME)

$(NAME):
	gcc -o $(NAME) main.c 

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME).a

re: fclean all
